# Generated by Django 4.1 on 2023-03-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_image_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
