# Generated by Django 4.1 on 2023-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_image_delete_fileupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
    ]
