# Generated by Django 4.1 on 2023-04-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_delete_image_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
