# Generated by Django 4.1 on 2023-04-03 08:12

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=embed_video.fields.EmbedVideoField(default="", null=True),
        ),
    ]
